project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Tony Stone"

  page-footer:
    center: "Copyright &copy; 2023 Tony Stone."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


