project:
  type: website
  output-dir: docs
  resources: 
    - "favicon.ico"
    - "*.png"
    - "site.webmanifest"

website:
  page-navigation: true
  title: "Tony Stone"

  page-footer:
    center: "Copyright &copy; 2023 Tony Stone."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
