---
title: "Tony Stone :: Presentations"
about:
  id: hero-heading
  template: trestles
  image-shape: rectangle
  links:
    - icon: github
      text: Github
      href: https://github.com/tony-stone
    - text: <span class="icon-orcid"></span>ORCiD
      href: https://orcid.org/0000-0002-0167-3800
---

::: {#hero-heading}
## Presentations

### 2024

**21 Aug 2024 - ECHO-CCS investigators**

#### [Education and longer-term Health Outcomes for Childhood Cancer Survivors (ECHO-CCS) project overview](https://tony-stone.github.io/echo-ccs-kickoff)

**6 Mar 2024 - ONS Linkage Expert Group**

An (updated) exploration of patient, organisational and spatio-temporal characteristics in administrative hospital data in England.

#### [Which people are most affected by changes to data linkage methodology? (updated)](https://tony-stone.github.io/linkage-methodology-impact-ons)

**6 Mar 2024 - ONS Linkage Expert Group**

An (updated) exploration of patient, organisational and spatio-temporal characteristics in administrative hospital data in England.

### 2023

#### [Which people are most affected by changes to data linkage methodology?](https://tony-stone.github.io/adruk-conf)

**16 Nov 2023 - ADR UK Conference, Birmingham**

An exploration of patient, organisational and spatio-temporal characteristics in administrative hospital data in England.

#### [Keeping a Tidy House](https://tony-stone.github.io/keeping-a-tidy-house)

**21 Sep 2023 - ECHILD User Group, London**

A presentation about structuring projects and code based on guidance in the ONS's Duck Book.

#### [Stuck in the middle?](https://tony-stone.github.io/ECHILD-eval-presentation)

**6 Sep 2023 - Private Audience, Edinburgh**

Plans and problems around the ECHILD record linkage evaluation.
:::
